FROM node:22.1.0-alpine3.18

EXPOSE 6006

WORKDIR /app

VOLUME [ "/app/node_modules" ]

COPY postcss.config.cjs .

COPY panda.config.ts .

COPY package*.json .

RUN npm install

CMD ["npm", "run", "storybook" ]
